version: '3.8'
services:
  rabbitmq:
    hostname: rabbitmq
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    volumes:
      - ./.docker/rabbitmq/etc/:/etc/rabbitmq/
      - ./.docker/rabbitmq/data/:/var/lib/rabbitmq/
      - ./.docker/rabbitmq/logs/:/var/log/rabbitmq/
    environment:
      RABBITMQ_DEFAULT_USER: username
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - "5672:5672"
      - "15672:15672"
    expose:
      - "5672"
    
  businessservice:
    hostname: businesservice
    build: 
      context: ./FS-BusinessesService/BusinessService
      dockerfile: Dockerfile
    ports:
    - "5003:5003"
    - "4003:4003"
    environment:
      - ASPNETCORE_URLS=https://+:5003;http://+:4003
    
  orderservice:
    hostname: orderservice
    build:
      context: ./FS-OrdersService/OrderService
      dockerfile: Dockerfile
    ports:
      - "5002:5002"
      - "4002:4002"
    environment:
      - ASPNETCORE_URLS=https://+:5002;http://+:4002
  paymentservice:
      build:
        context: ./PaymentService/PaymentService
        dockerfile: Dockerfile
      ports:
        - "5004:5004"
        - "4004:4004"
      environment:
        - ASPNETCORE_URLS=https://+:5004;http://+:4004
        - RabbitMQConnectionString=amqp://username:password@rabbitmq:5672

  packageservice:
      build:
        context: ./FS-PackagesService/PackageService
        dockerfile: Dockerfile
      ports:
        - "5001:5001"
        - "4001:4001"
      environment:
        - ASPNETCORE_URLS=https://+:5001;http://+:4001
        - RabbitMQConnectionString=amqp://username:password@rabbitmq:5672
  authservice:
      build:
        context: ./FS-Auth/FS_Auth
        dockerfile: Dockerfile
      ports:
        - "5000:5000"
        - "4000:4000"
      environment:
          - ASPNETCORE_URLS=https://+:5000;http://+:4000
  gateway:
      build:
        context: ./FS-Gateway/FS-Gateway
        dockerfile: Dockerfile
      ports:
        - "4999:4999"
        - "3999:3999"
      environment:
        - ASPNETCORE_URLS=https://+:4999;http://+:3999