services:
  businessservice:
    build: 
      context: ./FS-BusinessesService/BusinessService
      dockerfile: Dockerfile
    ports:
    - "5003:5003"
    - "4003:4003"
    environment:
      - ASPNETCORE_URLS=https://+:5003;http://+:4003
    
  orderservice:
    build:
      context: ./FS-OrdersService/OrderService
      dockerfile: Dockerfile
    ports:
      - "5002:5002"
      - "4002:4002"
    environment:
      - ASPNETCORE_URLS=https://+:5002;http://+:4002
  paymentservice:
      build:
        context: ./PaymentService/PaymentService
        dockerfile: Dockerfile
      ports:
        - "5004:5004"
        - "4004:4004"
      environment:
        - ASPNETCORE_URLS=https://+:5004;http://+:4004
  packageservice:
      build:
        context: ./FS-PackagesService/PackageService
        dockerfile: Dockerfile
      ports:
        - "5001:5001"
        - "4001:4001"
      environment:
        - ASPNETCORE_URLS=https://+:5001;http://+:4001
  authservice:
      build:
        context: ./FS-Auth/FS_Auth
        dockerfile: Dockerfile
      ports:
        - "5000:5000"
        - "4000:4000"
      environment:
          - ASPNETCORE_URLS=https://+:5000;http://+:4000
  gateway:
      build:
        context: ./FS-Gateway/FS-Gateway
        dockerfile: Dockerfile
      ports:
        - "4999:4999"
        - "3999:3999"
      environment:
        - ASPNETCORE_URLS=https://+:4999;http://+:3999