// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OrderStateMachine;

namespace OrderStateMachine.Migrations
{
    [DbContext(typeof(OrderSagaDbContext))]
    [Migration("20210126164908_start")]
    partial class start
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("FS_Saga.OrderStateMachine.OrderStateData", b =>
                {
                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("char(36)");

                    b.Property<string>("CheckoutSessionId")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("CurrentState")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64) CHARACTER SET utf8mb4");

                    b.Property<DateTime?>("OrderCancelDateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("OrderCollectedDateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("OrderCreationDateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("char(36)");

                    b.Property<string>("PaymentMethod")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("CorrelationId");

                    b.ToTable("OrderStateData");
                });

            modelBuilder.Entity("MessagingContracts.Orders.PackageId", b =>
                {
                    b.Property<Guid>("value")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("OrderStateDataCorrelationId")
                        .HasColumnType("char(36)");

                    b.HasKey("value");

                    b.HasIndex("OrderStateDataCorrelationId");

                    b.ToTable("PackageId");
                });

            modelBuilder.Entity("MessagingContracts.Orders.PackageId", b =>
                {
                    b.HasOne("FS_Saga.OrderStateMachine.OrderStateData", null)
                        .WithMany("PackagesId")
                        .HasForeignKey("OrderStateDataCorrelationId");
                });

            modelBuilder.Entity("FS_Saga.OrderStateMachine.OrderStateData", b =>
                {
                    b.Navigation("PackagesId");
                });
#pragma warning restore 612, 618
        }
    }
}
